SELECT YEAR(a.SALES_DATE) YEAR, MONTH(a.SALES_DATE) MONTH, b.GENDER, COUNT(DISTINCT(a.USER_ID)) USERS
FROM ONLINE_SALE a
INNER JOIN USER_INFO b ON b.USER_ID = a.USER_ID AND b.GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3