-- 코드를 입력하세요
SELECT a.CAR_ID, a.CAR_TYPE, FLOOR(a.DAILY_FEE * 30 * (1 - (c.DISCOUNT_RATE / 100))) AS FEE
FROM CAR_RENTAL_COMPANY_CAR a
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b ON b.CAR_ID = a.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c ON c.CAR_TYPE = a.CAR_TYPE AND DURATION_TYPE = '30일 이상'
WHERE a.CAR_TYPE IN ('세단', 'SUV')
GROUP BY a.CAR_ID 
HAVING (MAX(END_DATE) < '2022-11-01' OR MAX(END_DATE) IS NULL) 
    AND FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, a.CAR_TYPE ASC, a.CAR_ID ASC