WITH RECURSIVE data AS (
    SELECT ID, 1 g
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT e.ID, d.g + 1
    FROM ECOLI_DATA e
    INNER JOIN data d ON e.PARENT_ID = d.ID
)
SELECT ID
FROM data
WHERE g = 3
ORDER BY 1