WITH x AS (
select FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
from REST_INFO
GROUP BY FOOD_TYPE)
SELECT a.FOOD_TYPE, a.REST_ID, a.REST_NAME, a.FAVORITES
FROM REST_INFO a
INNER JOIN x ON x.FOOD_TYPE = a.FOOD_TYPE AND x.FAVORITES = a.FAVORITES
ORDER BY 1 DESC