SELECT YEAR(a.sales_date) AS YEAR,
    MONTH(a.sales_date) AS MONTH, 
    count(DISTINCT a.USER_ID) AS PUCHASED_USERS, 
    ROUND(count(DISTINCT a.USER_ID)/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) AS PUCHASED_RATIO
FROM ONLINE_SALE a
INNER JOIN USER_INFO b ON b.USER_ID = a.USER_ID AND YEAR(b.JOINED) = 2021
GROUP BY 1,2
ORDER BY 1,2