WITH ids AS (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5)
SELECT MONTH(a.START_DATE) AS MONTH, a.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY a
INNER JOIN ids b ON b.CAR_ID = a.CAR_ID
WHERE DATE_FORMAT(a.START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY 1, 2
ORDER BY 1, 2 DESC