WITH ranked AS (
    SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) num
    FROM ECOLI_DATA
)
SELECT ID,
    CASE WHEN num <= 0.25 THEN "CRITICAL"
    WHEN num <= 0.5 THEN "HIGH"
    WHEN num <= 0.75 THEN "MEDIUM"
    ELSE "LOW" END COLONY_NAME
FROM ranked
ORDER BY 1