-- 코드를 입력하세요
SELECT a.FLAVOR
FROM FIRST_HALF a 
INNER JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS total FROM JULY GROUP BY FLAVOR) b
ON b.FLAVOR = a.FLAVOR
GROUP BY a.FLAVOR
ORDER BY SUM(a.TOTAL_ORDER) + b.total DESC 
LIMIT 3