SELECT b.USER_ID, b.NICKNAME, SUM(a.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD a
INNER JOIN USED_GOODS_USER b ON b.USER_ID = a.WRITER_ID
WHERE a.STATUS = 'DONE'
GROUP BY 1
HAVING TOTAL_SALES >= 700000
ORDER BY 3