WITH RECURSIVE generation AS ( 
    SELECT ID, PARENT_ID, 1 GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL 
    UNION ALL
    SELECT e.ID, e.PARENT_ID, g.GENERATION + 1
    FROM ECOLI_DATA e
    INNER JOIN generation g ON e.PARENT_ID = g.ID
)
SELECT COUNT(*) COUNT, g1.GENERATION
FROM generation g1
LEFT JOIN generation g2 ON g1.ID = g2.PARENT_ID
WHERE g2.ID IS NULL
GROUP BY 2
ORDER BY 2
