SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(bs.SALES * b.PRICE) TOTAL_SALES
FROM BOOK_SALES bs
INNER JOIN BOOK b ON b.BOOK_ID = bs.BOOK_ID
INNER JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE DATE_FORMAT(bs.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY 1, 3
ORDER BY 1, 3 DESC