SELECT 
    h.HISTORY_ID,
    TRUNCATE((DATEDIFF(h.END_DATE, h.START_DATE) + 1) * c.DAILY_FEE * (1 - (IFNULL(p.DISCOUNT_RATE, 0) / 100)), 0)FEE
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY h
INNER JOIN 
    CAR_RENTAL_COMPANY_CAR c ON h.CAR_ID = c.CAR_ID AND c.CAR_TYPE = "트럭"
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN p ON c.CAR_TYPE = p.CAR_TYPE
    AND CASE
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 90 THEN "90일 이상"
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 30 THEN "30일 이상"
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 7 THEN "7일 이상"
            ELSE NULL 
        END = p.DURATION_TYPE
ORDER BY 2 DESC, 1 DESC;