SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID,	r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD b
INNER JOIN USED_GOODS_REPLY r ON r.BOARD_ID = b.BOARD_ID 
WHERE DATE_FORMAT(b.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY 6 ASC, 1 ASC