SELECT a.PRODUCT_ID, b.PRODUCT_NAME, SUM(a.AMOUNT) * b.PRICE AS TOTAL_SALES
FROM FOOD_ORDER a 
INNER JOIN FOOD_PRODUCT b ON b.PRODUCT_ID = a.PRODUCT_ID
WHERE date_format(a.PRODUCE_DATE,  '%Y-%m') = '2022-05'
GROUP BY a.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, a.PRODUCT_ID ASC