WITH checked AS (
    SELECT EMP_NO, 
        CASE WHEN AVG(SCORE) >= 96 THEN 'S'
        WHEN AVG(SCORE) >= 90 THEN 'A'
        WHEN AVG(SCORE) >= 80 THEN 'B'
        ELSE 'C' END GRADE, 
        CASE WHEN AVG(SCORE) >= 96 THEN 0.2
        WHEN AVG(SCORE) >= 90 THEN 0.15
        WHEN AVG(SCORE) >= 80 THEN 0.10
        ELSE 0 END per
    FROM HR_GRADE
    GROUP BY 1
)
SELECT e.EMP_NO, e.EMP_NAME, c.GRADE, e.SAL * c.per BONUS
FROM HR_EMPLOYEES e
INNER JOIN checked c USING (EMP_NO)
ORDER BY 1