WITH data AS (
    SELECT t.ITEM_ID
    FROM ITEM_INFO i
    INNER JOIN ITEM_TREE t ON i.ITEM_ID = t.PARENT_ITEM_ID
    WHERE i.RARITY = "RARE"
)
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT * FROM data)
ORDER BY 1 DESC