WITH max_size AS (
    SELECT YEAR(DIFFERENTIATION_DATE) y, MAX(SIZE_OF_COLONY) size
    FROM ECOLI_DATA
    GROUP BY 1
)
SELECT m.y 'YEAR', m.size - e.SIZE_OF_COLONY YEAR_DEV, e.ID
FROM ECOLI_DATA e
INNER JOIN max_size m ON YEAR(e.DIFFERENTIATION_DATE) = m.y
ORDER BY 1, 2