SELECT a.APNT_NO, p.PT_NAME, a.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
FROM APPOINTMENT a
INNER JOIN PATIENT p ON p.PT_NO = a.PT_NO
INNER JOIN DOCTOR d ON d.DR_ID = a.MDDR_ID
WHERE date_format(a.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
AND a.MCDP_CD = 'CS'
AND a.APNT_CNCL_YN = 'N'
ORDER BY 6 ASC