WITH ranked AS (
    SELECT FISH_TYPE, ID, LENGTH, RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) num
    FROM FISH_INFO
)
SELECT r.ID, i.FISH_NAME, r.LENGTH
FROM ranked r
INNER JOIN FISH_NAME_INFO i USING (FISH_TYPE)
WHERE r.num = 1
ORDER BY 1