WITH ranked AS (
    SELECT EMP_NO, SUM(SCORE) SCORE, RANK() OVER(ORDER BY SUM(SCORE) DESC) num
    FROM HR_GRADE
    GROUP BY 1
)
SELECT r.SCORE, r.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM ranked r
INNER JOIN HR_EMPLOYEES e USING (EMP_NO)
WHERE r.num = 1