SELECT b.BOOK_ID, a.AUTHOR_NAME, date_format(b.PUBLISHED_DATE, '%Y-%m-%d')AS PUBLISHED_DATE
FROM BOOK b
INNER JOIN AUTHOR a ON a.AUTHOR_ID = b.AUTHOR_ID
WHERE b.CATEGORY = '경제'
ORDER BY b.PUBLISHED_DATE ASC